spring.application.name=itqgroup-service
logging.level.com.itqgroup.service=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

postgres.schema=event
postgres.username=postgres
postgres.password=secret
postgres.host=postgres
postgres.custom.port=5432
postgres.database=platform

spring.datasource.url=jdbc:postgresql://${postgres.host}:${postgres.custom.port}/${postgres.database}?currentSchema=${postgres.schema}
spring.datasource.username=${postgres.username}
spring.datasource.password=${postgres.password}

application.limit.pageSize=10
application.generation.document.value=100
application.worker.batch.size=10
application.worker.cron.expression=0 * * * * *
application.service.url=http://localhost:8082
server.port=8082